
import java.awt.Dimension;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.ArrayList;

import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
//import jdk.internal.util.xml.impl.Input;
//import sun.font.TrueTypeFont;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
class GuiOutputStream extends OutputStream {

	JTextArea textArea;

	public GuiOutputStream(JTextArea textArea) {
		this.textArea = textArea;
	}

	@Override
	public void write(int data) throws IOException {
		textArea.append(new String(new byte[] { (byte) data }));
		textArea.setCaretPosition(textArea.getDocument().getLength());
	}
}

/**
 *
 * @author Adrian Blanco
 */
public class MyGui extends javax.swing.JFrame {

	private MainAgent mainAgent;
	private Thread process;

	/**
	 * Creates new form NewGui
	 */
	public MyGui(MainAgent agent) {
		mainAgent = agent;
		initComponents();
		setSize(new Dimension(700, 700)); // Window size
		setLocationRelativeTo(null);// Posicion de la ventana en el centro
		btnStop.setEnabled(false);
		btnResume.setEnabled(false);
		taVerbose.setEditable(false);
		txpGamesPlayed.setEditable(false);
		txpNumPlayer.setEditable(false);
		txpRounds.setEditable(false);
		tpConfessions.setEditable(false);
		tpBetray.setEditable(true);
		GuiOutputStream rawout = new GuiOutputStream(taVerbose);
		System.setOut(new PrintStream(rawout, true));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jDialog1 = new javax.swing.JDialog();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane6 = new javax.swing.JScrollPane();
		txNewRounds = new javax.swing.JTextPane();
		btnOkRounds = new javax.swing.JButton();
		jScrollPane8 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		consoleLbl = new java.awt.Label();
		lbNumplayers = new javax.swing.JLabel();
		lbGames = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txpNumPlayer = new javax.swing.JTextPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		txpGamesPlayed = new javax.swing.JTextPane();
		lblStatistics = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane5 = new javax.swing.JScrollPane();
		taVerbose = new javax.swing.JTextArea();
		btnStop = new javax.swing.JButton();
		btnResume = new javax.swing.JButton();
		jScrollPane4 = new javax.swing.JScrollPane();
		txpRounds = new javax.swing.JTextPane();
		lbConfessions = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		tpConfessions = new javax.swing.JTextPane();
		jScrollPane7 = new javax.swing.JScrollPane();
		tpBetray = new javax.swing.JTextPane();
		jScrollPane9 = new javax.swing.JScrollPane();
		tablePlayers = new javax.swing.JTable();
		jMenuBar1 = new javax.swing.JMenuBar();
		startMenu = new javax.swing.JMenu();
		newGame = new javax.swing.JMenuItem();
		numberRounds = new javax.swing.JMenuItem();
		editMenu = new javax.swing.JMenu();
		resetPlayers = new javax.swing.JMenuItem();
		removePlayer = new javax.swing.JMenuItem();
		windowMenu = new javax.swing.JMenu();
		verbose = new javax.swing.JCheckBoxMenuItem();
		helpMenu = new javax.swing.JMenu();
		about = new javax.swing.JMenuItem();

		jDialog1.setTitle("Number of rounds");

		jLabel2.setText("Introduce the new number of rounds:");

		txNewRounds.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		txNewRounds.setAutoscrolls(false);

		jScrollPane6.setViewportView(txNewRounds);

		btnOkRounds.setText("Ok");
		btnOkRounds.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOkRoundsActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
		jDialog1.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jDialog1Layout.createSequentialGroup().addGroup(jDialog1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jDialog1Layout.createSequentialGroup().addContainerGap()
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(3, 3, 3)
								.addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
						.addGroup(jDialog1Layout.createSequentialGroup().addGap(112, 112, 112).addComponent(btnOkRounds,
								javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(35, 35, 35)));
		jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jDialog1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(btnOkRounds).addGap(28, 28, 28)));

		jTable1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane8.setViewportView(jTable1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		consoleLbl.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
		consoleLbl.setText("Console:");

		lbNumplayers.setText("Number of players:");

		lbGames.setText("Games played:");

		txpNumPlayer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jScrollPane1.setViewportView(txpNumPlayer);

		txpGamesPlayed.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jScrollPane2.setViewportView(txpGamesPlayed);

		lblStatistics.setText("Statistics:");

		jLabel1.setText("Rounds:");

		taVerbose.setColumns(20);
		taVerbose.setRows(5);
		jScrollPane5.setViewportView(taVerbose);

		btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pause.png"))); // NOI18N
		btnStop.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnStopActionPerformed(evt);
			}
		});

		btnResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.png"))); // NOI18N
		btnResume.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnResumeActionPerformed(evt);
			}
		});

		txpRounds.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jScrollPane4.setViewportView(txpRounds);

		lbConfessions.setText("Confessions: ");

		jLabel3.setText("Betrayals: ");

		jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jScrollPane3.setViewportView(tpConfessions);

		tpBetray.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jScrollPane7.setViewportView(tpBetray);

		tablePlayers.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Players", "Games", "Points", "Avg Points", "Games won" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jScrollPane9.setViewportView(tablePlayers);

		startMenu.setText("Start");

		newGame.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
		newGame.setText("New Game");
		newGame.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newGameActionPerformed(evt);
			}
		});
		startMenu.add(newGame);

		numberRounds.setText("Number of rounds");
		numberRounds.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				numberRoundsActionPerformed(evt);
			}
		});
		startMenu.add(numberRounds);

		jMenuBar1.add(startMenu);

		editMenu.setText("Edit");

		resetPlayers.setText("Reset players");
		resetPlayers.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetPlayersActionPerformed(evt);
			}
		});
		editMenu.add(resetPlayers);

		removePlayer.setText("Remove player");
		editMenu.add(removePlayer);

		jMenuBar1.add(editMenu);

		windowMenu.setText("Window");

		verbose.setSelected(true);
		verbose.setText("Verbose on/off");
		verbose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				verboseActionPerformed(evt);
			}
		});
		windowMenu.add(verbose);

		jMenuBar1.add(windowMenu);

		helpMenu.setText("Help");

		about.setText("About");
		about.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aboutActionPerformed(evt);
			}
		});
		helpMenu.add(about);

		jMenuBar1.add(helpMenu);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
												.createSequentialGroup().addContainerGap().addComponent(jScrollPane9))
										.addGroup(layout
												.createSequentialGroup().addGap(12, 12, 12).addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addComponent(
																btnResume, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
																javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		11, Short.MAX_VALUE)
																.addComponent(btnStop,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 85,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup().addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(lbGames).addComponent(lbNumplayers)
																.addComponent(
																		lblStatistics)
																.addComponent(jLabel3).addComponent(lbConfessions)
																.addComponent(jLabel1))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jScrollPane1)
																		.addComponent(jScrollPane4)
																		.addComponent(jScrollPane2)
																		.addComponent(jScrollPane3)
																		.addComponent(jScrollPane7,
																				javax.swing.GroupLayout.Alignment.TRAILING))))
												.addGap(72, 72, 72)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jScrollPane5,
																javax.swing.GroupLayout.PREFERRED_SIZE, 287,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(consoleLbl,
																javax.swing.GroupLayout.PREFERRED_SIZE, 87,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(67, 67, 67)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(consoleLbl, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(lblStatistics))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup().addGap(6, 6, 6).addComponent(lbGames))
								.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(12, 12, 12).addComponent(lbNumplayers))
								.addGroup(layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(lbConfessions, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(31, 31, 31)
										.addComponent(btnResume, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE))))
						.addComponent(jScrollPane5))
				.addGap(18, 18, 18).addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 234,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(45, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void newGameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newGameActionPerformed

		mainAgent.newGame();
		btnStop.setEnabled(true);
		btnResume.setEnabled(false);
		newGame.setEnabled(false);
		resetPlayers.setEnabled(false);
		removePlayer.setEnabled(false);
	}// GEN-LAST:event_newGameActionPerformed

	private void numberRoundsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numberRoundsActionPerformed
		jDialog1.setVisible(true);
		jDialog1.setSize(361, 120);
		jDialog1.setLocationRelativeTo(null);
		btnOkRounds.setEnabled(false);
	}// GEN-LAST:event_numberRoundsActionPerformed

	private void verboseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_verboseActionPerformed
		if (verbose.isSelected()) {
			taVerbose.setVisible(true);
		} else {
			taVerbose.setVisible(false);
		}
	}// GEN-LAST:event_verboseActionPerformed

	private void aboutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aboutActionPerformed
		About_dialog aboutDialog = new About_dialog(this, false);
		aboutDialog.setVisible(true);
		aboutDialog.setLocationRelativeTo(null);
	}// GEN-LAST:event_aboutActionPerformed

	private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResumeActionPerformed
		mainAgent.setResume();
		btnResume.setEnabled(false);
		btnStop.setEnabled(true);
		newGame.setEnabled(false);
	}// GEN-LAST:event_btnResumeActionPerformed

	private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnStopActionPerformed
		mainAgent.setStop();
		btnResume.setEnabled(true);
		btnStop.setEnabled(false);
		newGame.setEnabled(true);
	}// GEN-LAST:event_btnStopActionPerformed

	private void btnOkRoundsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnOkRoundsActionPerformed
		int newNumRounds = Integer.valueOf(txNewRounds.getText());
		if (newNumRounds > 0) {
			this.setNumRounds(newNumRounds);
			mainAgent.newNumRounds(newNumRounds);

		}
		jDialog1.dispose();
	}// GEN-LAST:event_btnOkRoundsActionPerformed

	private void resetPlayersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetPlayersActionPerformed
		mainAgent.resetStats();
	}// GEN-LAST:event_resetPlayersActionPerformed

	public void initTable(ArrayList<String> playersNames) {
		DefaultTableModel model = (DefaultTableModel) tablePlayers.getModel();

		for (String name : playersNames) {
			Object[] row = { name, 0, 0, 0, 0 };
			model.addRow(row);
		}

	}

	public void updateTable(String name, String games, String points, String avg, String gamesWon) {
		DefaultTableModel model = (DefaultTableModel) tablePlayers.getModel();
		int rows = model.getRowCount();
		for (int i = 0; i < rows; i++) {
			if (model.getValueAt(i, 0).equals(name.trim())) {
				model.setValueAt(games, i, 1);
				model.setValueAt(points, i, 2);
				model.setValueAt(avg, i, 3);
				model.setValueAt(gamesWon, i, 4);
			}
		}
	}

	public void clearTable(boolean eraseAll) {
		DefaultTableModel model = (DefaultTableModel) tablePlayers.getModel();
		if (eraseAll) {
			model.setRowCount(0);
		} else {
			int rows = model.getRowCount();
			for (int i = 0; i < rows; i++) {
				model.setValueAt(0, i, 1);
				model.setValueAt(0, i, 2);
				model.setValueAt(0, i, 3);
				model.setValueAt(0, i, 4);
			}
		}
	}

	public void setNumberGames(int numGames) {
		this.txpGamesPlayed.setText(String.valueOf(numGames));
	}

	public void setNumberPlayers(int numPlayers) {
		this.txpNumPlayer.setText(String.valueOf(numPlayers));
	}

	public void setNumConfess(int numConf) {
		this.tpConfessions.setText(String.valueOf(numConf));
	}

	public void setNumBetray(int numBetray) {
		this.tpBetray.setText(String.valueOf(numBetray));
	}

	public void updateConfBetray(int conf, int betray) {
		this.setNumConfess(conf);
		this.setNumBetray(betray);
	}

	public void setNumRounds(int numRounds) {
		this.txpRounds.setText(String.valueOf(numRounds));
	}

	public void log(String log) {
		System.out.println(log);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;

				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new MyGui(MainAgent).setVisible(true);
//			}
//		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem about;
	public javax.swing.JButton btnOkRounds;
	public javax.swing.JButton btnResume;
	public javax.swing.JButton btnStop;
	private java.awt.Label consoleLbl;
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JDialog jDialog1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JScrollPane jScrollPane8;
	private javax.swing.JScrollPane jScrollPane9;
	private javax.swing.JTable jTable1;
	private javax.swing.JLabel lbConfessions;
	private javax.swing.JLabel lbGames;
	private javax.swing.JLabel lbNumplayers;
	private javax.swing.JLabel lblStatistics;
	public javax.swing.JMenuItem newGame;
	public javax.swing.JMenuItem numberRounds;
	public javax.swing.JMenuItem removePlayer;
	public javax.swing.JMenuItem resetPlayers;
	private javax.swing.JMenu startMenu;
	private javax.swing.JTextArea taVerbose;
	private javax.swing.JTable tablePlayers;
	private javax.swing.JTextPane tpBetray;
	private javax.swing.JTextPane tpConfessions;
	private javax.swing.JTextPane txNewRounds;
	private javax.swing.JTextPane txpGamesPlayed;
	private javax.swing.JTextPane txpNumPlayer;
	private javax.swing.JTextPane txpRounds;
	private javax.swing.JCheckBoxMenuItem verbose;
	private javax.swing.JMenu windowMenu;
	// End of variables declaration//GEN-END:variables

}
